# Generated by Django 3.0 on 2023-10-30 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0005_auto_20231030_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
    ]
